const CONFIG={
  clientId:"be1d4ce0d9ff4d4eb5a28a4a175c5e33",
  redirectUri:window.location.origin+window.location.pathname,
  scope:"playlist-read-private"
};const $=s=>document.querySelector(s);const state={token:null,playlists:[],selected:null,songs:[],round:0,score:0,clipIndex:0,clips:[.1,.5,1,2,5],current:null};
const els={spotifyBtn:$('#spotifyBtn'),status:$('#status'),playlistList:$('#playlistList'),startBtn:$('#startBtn'),setup:$('#setup'),game:$('#game'),result:$('#result'),playlistTitle:$('#playlistTitle'),roundLabel:$('#roundLabel'),progressBar:$('#progressBar'),timer:$('#timer'),playBtn:$('#playBtn'),skipBtn:$('#skipBtn'),answer:$('#guess'),answerBtn:$('#answerBtn'),answerBox:$('#answerBox'),audio:$('#audio'),score:$('#score'),resultText:$('#resultText'),againBtn:$('#againBtn'),quitBtn:$('#quitBtn')};
function base64url(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sha256(s){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))}
function randomString(n=64){const a=new Uint8Array(n);crypto.getRandomValues(a);return [...a].map(x=>(x%36).toString(36)).join('')}
async function login(){if(CONFIG.clientId.startsWith('YOUR_')){alert('Ajoute ton Spotify Client ID dans app.js, ligne 1.');return}const verifier=randomString();const challenge=base64url(await sha256(verifier));localStorage.setItem('pkce_verifier',verifier);const stateToken=randomString(16);localStorage.setItem('oauth_state',stateToken);const u=new URL('https://accounts.spotify.com/authorize');u.search=new URLSearchParams({client_id:CONFIG.clientId,response_type:'code',redirect_uri:CONFIG.redirectUri,scope:CONFIG.scope,state:stateToken,code_challenge_method:'S256',code_challenge:challenge});location.href=u}
async function exchangeCode(code){const verifier=localStorage.getItem('pkce_verifier');const body=new URLSearchParams({client_id:CONFIG.clientId,grant_type:'authorization_code',code,redirect_uri:CONFIG.redirectUri,code_verifier:verifier});const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error('Spotify token error');const d=await r.json();state.token=d.access_token;localStorage.setItem('spotify_token',state.token);history.replaceState({},'',CONFIG.redirectUri);localStorage.removeItem('pkce_verifier');localStorage.removeItem('oauth_state')}
async function spotify(path){const r=await fetch('https://api.spotify.com/v1'+path,{headers:{Authorization:`Bearer ${state.token}`}});if(r.status===401){localStorage.removeItem('spotify_token');throw new Error('Session Spotify expirée');}if(!r.ok)throw new Error(`Spotify ${r.status}`);return r.json()}
async function loadPlaylists(){state.playlists=[];let url='/me/playlists?limit=50';while(url){const d=await spotify(url);state.playlists.push(...d.items);url=d.next?new URL(d.next).pathname+new URL(d.next).search:''}renderPlaylists()}
function renderPlaylists(){els.status.textContent=`${state.playlists.length} playlist${state.playlists.length>1?'s':''}`;els.playlistList.innerHTML='';state.playlists.filter(p=>p&&p.id).forEach(p=>{const b=document.createElement('button');b.className='playlist';b.innerHTML=`<img src="${p.images?.[0]?.url||''}" alt=""><div><strong>${esc(p.name)}</strong><span>${p.items?.total??p.tracks?.total??''} titres</span></div>`;b.onclick=()=>{document.querySelectorAll('.playlist').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selected=p;els.startBtn.disabled=false};els.playlistList.appendChild(b)})}
async function loadSongs(id){let songs=[],url=`/playlists/${encodeURIComponent(id)}/items?limit=50&market=FR`;while(url){const d=await spotify(url);for(const x of d.items||[]){const t=x.item;if(t?.type==='track'&&t.name)songs.push(t)}url=d.next?new URL(d.next).pathname+new URL(d.next).search:''}return songs}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function normalize(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function chooseSong(){state.current=state.songs[Math.floor(Math.random()*state.songs.length)];state.clipIndex=0;els.timer.textContent=`${state.clips[0]} s`;els.answer.value='';els.answerBox.classList.add('hidden');els.hint.textContent='Écoute l’extrait.';els.progressBar.style.width=`${state.round/state.songs.length*100}%`;setAudioPreview();}
async function setAudioPreview(){els.audio.pause();els.audio.removeAttribute('src');const q=encodeURIComponent(`${state.current.name} ${state.current.artists?.[0]?.name||''}`);try{const r=await fetch(`https://itunes.apple.com/search?term=${q}&entity=song&limit=5&country=FR`);const d=await r.json();const target=normalize(state.current.name);const hit=(d.results||[]).find(x=>normalize(x.trackName)===target)||d.results?.[0];if(hit?.previewUrl){els.audio.src=hit.previewUrl;els.audio.load();els.hint.textContent='Extrait Apple Music/iTunes';}else els.hint.textContent='Aucun extrait disponible pour ce titre.'}catch(e){els.hint.textContent='Impossible de charger l’extrait.'}}
async function playClip(){if(!els.audio.src){await setAudioPreview()}if(!els.audio.src)return;const duration=state.clips[state.clipIndex];els.audio.currentTime=0;await els.audio.play();els.timer.textContent=`${duration} s`;setTimeout(()=>{els.audio.pause()},duration*1000)}
function reveal(){els.audio.pause();const t=state.current;els.answerBox.innerHTML=`<strong>${esc(t.name)}</strong><span>${esc((t.artists||[]).map(a=>a.name).join(', '))}</span>`;els.answerBox.classList.remove('hidden');els.hint.textContent='Réponse';}
function submit(){if(!state.current)return;const guess=normalize(els.answer.value);const title=normalize(state.current.name);const artist=normalize((state.current.artists||[]).map(a=>a.name).join(' '));if(guess&&(title.includes(guess)||artist.includes(guess))){state.score++;reveal();nextRound()}else{reveal();nextRound()}}
function skip(){if(state.clipIndex<state.clips.length-1){state.clipIndex++;els.timer.textContent=`${state.clips[state.clipIndex]} s`;playClip()}else reveal()}
function nextRound(){setTimeout(()=>{state.round++;if(state.round>=state.songs.length){endGame()}else chooseSong()},900)}
function endGame(){els.game.classList.add('hidden');els.result.classList.remove('hidden');els.score.textContent=`${state.score} / ${state.songs.length}`;els.resultText.textContent='Tu peux relancer une partie avec la même playlist.'}
async function start(){if(!state.selected)return;els.startBtn.disabled=true;els.status.textContent='Chargement…';state.songs=await loadSongs(state.selected.id);if(!state.songs.length){alert('Cette playlist ne contient aucun titre accessible.');els.startBtn.disabled=false;return}state.round=0;state.score=0;els.setup.classList.add('hidden');els.result.classList.add('hidden');els.game.classList.remove('hidden');els.playlistTitle.textContent=state.selected.name;chooseSong();els.status.textContent='Prêt'}
function init(){const params=new URLSearchParams(location.search);const code=params.get('code');const returnedState=params.get('state');if(code){if(returnedState!==localStorage.getItem('oauth_state')){alert('État OAuth invalide.');return}exchangeCode(code).then(loadPlaylists).then(()=>{els.spotifyBtn.textContent='Spotify connecté';els.status.textContent='Chargement…'}).catch(e=>alert(e.message))}else{const token=localStorage.getItem('spotify_token');if(token){state.token=token;els.spotifyBtn.textContent='Spotify connecté';loadPlaylists().catch(()=>{})}}}
els.spotifyBtn.onclick=login;els.startBtn.onclick=start;els.playBtn.onclick=playClip;els.skipBtn.onclick=skip;els.answerBtn.onclick=submit;els.answer.addEventListener('keydown',e=>{if(e.key==='Enter')submit()});els.quitBtn.onclick=()=>location.reload();els.againBtn.onclick=()=>{els.result.classList.add('hidden');els.setup.classList.remove('hidden');state.round=0;state.score=0};init();
